### PR TITLE
Nsew

### PR DESCRIPTION
**Pull request by neilstevenson**

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/72/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/72/platform-demos-pr-builder-72.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal on project churn-cassandra: Could not resolve dependencies for project com.hazelcast.platform.demos.telco.churn:churn-cassandra:jar:4.0: Could not find artifact com.google.guava:guava:jar:24.1.1-JRE in Hazelcast Private Release Repository (https://repository.hazelcast.com/release/) -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/73/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/73/platform-demos-pr-builder-73.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (default) on project churn-jet-jobs: There are test failures.
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/74/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/74/platform-demos-pr-builder-74.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M5:verify (default) on project churn-jet-jobs: There are test failures.
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/75/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/75/platform-demos-pr-builder-75.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/platform-demos-pr-builder/telco/churn/integration-tests/src/test/java/com/hazelcast/platform/demos/telco/churn/MyChurnDetectorIT.java:[53,52] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project churn-jet-jobs-it: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/platform-demos-pr-builder/telco/churn/integration-tests/src/test/java/com/hazelcast/platform/demos/telco/churn/MyChurnDetectorIT.java:[53,52] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/platform-demos-pr-builder/telco/churn/integration-tests/src/test/java/com/hazelcast/platform/demos/telco/churn/MyChurnDetectorIT.java:[53,13] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/platform-demos-pr-builder/telco/churn/integration-tests/src/test/java/com/hazelcast/platform/demos/telco/churn/MyChurnDetectorIT.java:[53,52] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/platform-demos-pr-builder/telco/churn/integration-tests/src/test/java/com/hazelcast/platform/demos/telco/churn/MyChurnDetectorIT.java:[53,13] cannot find symbol
--------------------------
</details>
</pre>

**Comment by neilstevenson** [comment]
verify

**Pull request merged**
