### PR TITLE
Cva

### PR DESCRIPTION
**Pull request by neilstevenson**
review

### CODE REVIEW

**Comment by kwart** [comment]
verify

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/33/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/33/platform-demos-pr-builder-33.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by kwart** [comment]
verify

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/34/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/34/platform-demos-pr-builder-34.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by kwart** [comment]
verify

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/35/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/35/platform-demos-pr-builder-35.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by neilstevenson** [comment]
verify

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/36/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/36/platform-demos-pr-builder-36.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/37/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/37/platform-demos-pr-builder-37.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by neilstevenson** [comment]
verify

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/38/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/38/platform-demos-pr-builder-38.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/39/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/39/platform-demos-pr-builder-39.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/40/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/40/platform-demos-pr-builder-40.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/41/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/41/platform-demos-pr-builder-41.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/42/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/42/platform-demos-pr-builder-42.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/43/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/43/platform-demos-pr-builder-43.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.13:build (default) on project cva-grafana: Could not build image: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
--------------------------
</details>
</pre>

**Pull request merged**
