### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by neilstevenson**
Latest tweaks to Trade Monitor and CVA

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/57/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/57/platform-demos-pr-builder-57.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/62/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/62/platform-demos-pr-builder-62.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal on project cva-abstract-hazelcast-node: Could not resolve dependencies for project com.hazelcast.platform.demos.banking.cva:cva-abstract-hazelcast-node:jar:4.0: Could not transfer artifact com.hazelcast.jet:hazelcast-jet-enterprise:jar:4.2 from/to Hazelcast Private Release Repository (https://repository.hazelcast.com/release/): Transfer failed for https://repository.hazelcast.com/release/com/hazelcast/jet/hazelcast-jet-enterprise/4.2/hazelcast-jet-enterprise-4.2.jar: Connect to akamai.bintray.com:443 [akamai.bintray.com/72.247.161.154] failed: Connection timed out (Connection timed out) -> [Help 1]
--------------------------
</details>
</pre>

**Comment by neilstevenson** [comment]
verify

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/84/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/84/platform-demos-pr-builder-84.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/85/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/85/platform-demos-pr-builder-85.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/86/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/86/platform-demos-pr-builder-86.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/87/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/87/platform-demos-pr-builder-87.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by hz-highfive** [comment]
The job `platform-demos-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/88/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/platform-demos-pr-builder/88/platform-demos-pr-builder-88.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by neilstevenson** [comment]
verify

**Pull request merged**
